image: "python:3.8"

before_script:
  - python --version
  - pip install -r requirements.txt

stages:
  - Static Analysis
  
flake8:
  stage: Static Analysis
  allow_failure: true
  script:
  - pip install flake8
  - flake8 --version
  - flake8 --max-line-length=100 *.py

pylint:
  stage: Static Analysis
  allow_failure: true
  script:
  - pip install pylint
  - pylint --version
  - pylint *.py

