#!/usr/bin/env python
#
# License: BSD
#   https://raw.githubusercontent.com/samiamlabs/dyno/master/LICENCE
#

import rospy
import uuid
import dialogflow_v2 as dialogflow

import std_msgs.msg as std_msgs
from dialogflow_ros.msg import QueryResult


class DialogflowNode:
    def __init__(self):
        rospy.init_node('dialogflow_node')
        
        #TODO: use params
        self.session_id = uuid.uuid4()
        self.project_id = 'dynotestsample'
        self.default_language = 'en-US'

        self.query_result_pub = rospy.Publisher('query_result', QueryResult, queue_size=10)
        rospy.Subscriber('text', std_msgs.String, self.text_callback)

    def text_callback(self, text_msg):
        query_result = self.detect_intent_text(text_msg.data, self.default_language)

        query_result_msg = QueryResult()
        query_result_msg.transcript = text_msg.data
        query_result_msg.fulfillment_text = query_result.fulfillment_text
        query_result_msg.intent_detection_confidence = query_result.intent_detection_confidence
        query_result_msg.intent = query_result.intent

        self.query_result_pub.publish(query_result_msg)

    def detect_intent_text(self, text, language_code):
        session_client = dialogflow.SessionsClient()

        session = session_client.session_path(self.project_id, self.session_id)
        rospy.loginfo('Session path: {}\n'.format(session))

        text_input = dialogflow.types.TextInput(
            text=text, language_code=language_code)

        query_input = dialogflow.types.QueryInput(text=text_input)

        response = session_client.detect_intent(
            session=session, query_input=query_input)

        rospy.loginfo('=' * 20)
        rospy.loginfo('Query text: {}'.format(response.query_result.query_text))
        rospy.loginfo('Detected intent: {} (confidence: {})\n'.format(
            response.query_result.intent.display_name,
            response.query_result.intent_detection_confidence))
        rospy.loginfo('Fulfillment text: {}\n'.format(
            response.query_result.fulfillment_text))
        return response.query_result


if __name__ == '__main__':
    dialogflow_node = DialogflowNode()
    rospy.spin()
